# Generated by Django 3.2.16 on 2022-10-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='score',
            field=models.IntegerField(default=0, verbose_name='امتیاز'),
        ),
    ]
